export const timezones = [
  { label: '(UTC-12:00) International Date Line West', value: 'Etc/GMT+12' },
  { label: '(UTC-11:00) Coordinated Universal Time-11', value: 'Etc/GMT+11' },
  { label: '(UTC-10:00) Hawaii', value: 'Pacific/Honolulu' },
  { label: '(UTC-09:00) Alaska', value: 'America/Anchorage' },
  { label: '(UTC-08:00) Pacific Time (US & Canada)', value: 'America/Los_Angeles' },
  { label: '(UTC-07:00) Mountain Time (US & Canada)', value: 'America/Denver' },
  { label: '(UTC-06:00) Central Time (US & Canada)', value: 'America/Chicago' },
  { label: '(UTC-05:00) Eastern Time (US & Canada)', value: 'America/New_York' },
  { label: '(UTC-03:00) Brasilia', value: 'America/Sao_Paulo' },
  { label: '(UTC+00:00) London', value: 'Europe/London' },
  { label: '(UTC+01:00) West Central Africa', value: 'Africa/Lagos' },
  { label: '(UTC+02:00) Central Africa Time', value: 'Africa/Johannesburg' },
  { label: '(UTC+03:00) Nairobi', value: 'Africa/Nairobi' },
  { label: '(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi', value: 'Asia/Kolkata' },
  { label: '(UTC+08:00) Beijing, Perth, Singapore, Hong Kong', value: 'Asia/Singapore' },
  { label: '(UTC+09:00) Tokyo, Seoul, Osaka, Sapporo, Yakutsk', value: 'Asia/Tokyo' },
  { label: '(UTC+10:00) Brisbane', value: 'Australia/Brisbane' },
  { label: '(UTC+12:00) Auckland, Wellington, Fiji, Kamchatka', value: 'Pacific/Auckland' },
];
